import * as address from "./address";
import * as answer from "./answer";
import * as app from "./app";
import * as avatar from "./avatar";
import * as cache from "./cache";
import * as carbon from "./carbon";
import * as contact from "./contact";
import * as crypto from "./crypto";
import * as currency from "./currency";
import * as db from "./db";
import * as email from "./email";
import * as emoji from "./emoji";
import * as evchargers from "./evchargers";
import * as event from "./event";
import * as file from "./file";
import * as forex from "./forex";
import * as fx from "./function";
import * as geocoding from "./geocoding";
import * as gifs from "./gifs";
import * as google from "./google";
import * as helloworld from "./helloworld";
import * as holidays from "./holidays";
import * as id from "./id";
import * as image from "./image";
import * as ip from "./ip";
import * as joke from "./joke";
import * as location from "./location";
import * as minecraft from "./minecraft";
import * as movie from "./movie";
import * as mq from "./mq";
import * as news from "./news";
import * as nft from "./nft";
import * as notes from "./notes";
import * as otp from "./otp";
import * as ping from "./ping";
import * as place from "./place";
import * as postcode from "./postcode";
import * as prayer from "./prayer";
import * as qr from "./qr";
import * as quran from "./quran";
import * as routing from "./routing";
import * as rss from "./rss";
import * as search from "./search";
import * as sentiment from "./sentiment";
import * as sms from "./sms";
import * as space from "./space";
import * as spam from "./spam";
import * as stock from "./stock";
import * as stream from "./stream";
import * as sunnah from "./sunnah";
import * as thumbnail from "./thumbnail";
import * as time from "./time";
import * as translate from "./translate";
import * as twitter from "./twitter";
import * as url from "./url";
import * as user from "./user";
import * as vehicle from "./vehicle";
import * as weather from "./weather";
import * as youtube from "./youtube";

export class Client {
  constructor(token: string) {
    this.addressService = new address.AddressService(token);
    this.answerService = new answer.AnswerService(token);
    this.appService = new app.AppService(token);
    this.avatarService = new avatar.AvatarService(token);
    this.cacheService = new cache.CacheService(token);
    this.carbonService = new carbon.CarbonService(token);
    this.contactService = new contact.ContactService(token);
    this.cryptoService = new crypto.CryptoService(token);
    this.currencyService = new currency.CurrencyService(token);
    this.dbService = new db.DbService(token);
    this.emailService = new email.EmailService(token);
    this.emojiService = new emoji.EmojiService(token);
    this.evchargersService = new evchargers.EvchargersService(token);
    this.eventService = new event.EventService(token);
    this.fileService = new file.FileService(token);
    this.forexService = new forex.ForexService(token);
    this.functionService = new fx.FunctionService(token);
    this.geocodingService = new geocoding.GeocodingService(token);
    this.gifsService = new gifs.GifsService(token);
    this.googleService = new google.GoogleService(token);
    this.helloworldService = new helloworld.HelloworldService(token);
    this.holidaysService = new holidays.HolidaysService(token);
    this.idService = new id.IdService(token);
    this.imageService = new image.ImageService(token);
    this.ipService = new ip.IpService(token);
    this.jokeService = new joke.JokeService(token);
    this.locationService = new location.LocationService(token);
    this.minecraftService = new minecraft.MinecraftService(token);
    this.movieService = new movie.MovieService(token);
    this.mqService = new mq.MqService(token);
    this.newsService = new news.NewsService(token);
    this.nftService = new nft.NftService(token);
    this.notesService = new notes.NotesService(token);
    this.otpService = new otp.OtpService(token);
    this.pingService = new ping.PingService(token);
    this.placeService = new place.PlaceService(token);
    this.postcodeService = new postcode.PostcodeService(token);
    this.prayerService = new prayer.PrayerService(token);
    this.qrService = new qr.QrService(token);
    this.quranService = new quran.QuranService(token);
    this.routingService = new routing.RoutingService(token);
    this.rssService = new rss.RssService(token);
    this.searchService = new search.SearchService(token);
    this.sentimentService = new sentiment.SentimentService(token);
    this.smsService = new sms.SmsService(token);
    this.spaceService = new space.SpaceService(token);
    this.spamService = new spam.SpamService(token);
    this.stockService = new stock.StockService(token);
    this.streamService = new stream.StreamService(token);
    this.sunnahService = new sunnah.SunnahService(token);
    this.thumbnailService = new thumbnail.ThumbnailService(token);
    this.timeService = new time.TimeService(token);
    this.translateService = new translate.TranslateService(token);
    this.twitterService = new twitter.TwitterService(token);
    this.urlService = new url.UrlService(token);
    this.userService = new user.UserService(token);
    this.vehicleService = new vehicle.VehicleService(token);
    this.weatherService = new weather.WeatherService(token);
    this.youtubeService = new youtube.YoutubeService(token);
  }

  addressService: address.AddressService;
  answerService: answer.AnswerService;
  appService: app.AppService;
  avatarService: avatar.AvatarService;
  cacheService: cache.CacheService;
  carbonService: carbon.CarbonService;
  contactService: contact.ContactService;
  cryptoService: crypto.CryptoService;
  currencyService: currency.CurrencyService;
  dbService: db.DbService;
  emailService: email.EmailService;
  emojiService: emoji.EmojiService;
  evchargersService: evchargers.EvchargersService;
  eventService: event.EventService;
  fileService: file.FileService;
  forexService: forex.ForexService;
  functionService: fx.FunctionService;
  geocodingService: geocoding.GeocodingService;
  gifsService: gifs.GifsService;
  googleService: google.GoogleService;
  helloworldService: helloworld.HelloworldService;
  holidaysService: holidays.HolidaysService;
  idService: id.IdService;
  imageService: image.ImageService;
  ipService: ip.IpService;
  jokeService: joke.JokeService;
  locationService: location.LocationService;
  minecraftService: minecraft.MinecraftService;
  movieService: movie.MovieService;
  mqService: mq.MqService;
  newsService: news.NewsService;
  nftService: nft.NftService;
  notesService: notes.NotesService;
  otpService: otp.OtpService;
  pingService: ping.PingService;
  placeService: place.PlaceService;
  postcodeService: postcode.PostcodeService;
  prayerService: prayer.PrayerService;
  qrService: qr.QrService;
  quranService: quran.QuranService;
  routingService: routing.RoutingService;
  rssService: rss.RssService;
  searchService: search.SearchService;
  sentimentService: sentiment.SentimentService;
  smsService: sms.SmsService;
  spaceService: space.SpaceService;
  spamService: spam.SpamService;
  stockService: stock.StockService;
  streamService: stream.StreamService;
  sunnahService: sunnah.SunnahService;
  thumbnailService: thumbnail.ThumbnailService;
  timeService: time.TimeService;
  translateService: translate.TranslateService;
  twitterService: twitter.TwitterService;
  urlService: url.UrlService;
  userService: user.UserService;
  vehicleService: vehicle.VehicleService;
  weatherService: weather.WeatherService;
  youtubeService: youtube.YoutubeService;
}
