name: Test Clients
on:
  push:
    branches:
      - main
      - beta

jobs:
  generate:
    name: Test Clients
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          path: clients
          #ref: main

      - name: Test
        working-directory: clients
        if: github.ref == 'refs/heads/beta'
        env:
          M3O_API_TOKEN: ${{ secrets.M3O_API_TOKEN }}
        run: |
          cd examples/helloworld/call
          npm init -y
          npm install --save m3o
          node callTheHelloworldService.js
